/**
 * Tests the static markup generated for directory child note rows.
 */

import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import { DirectoryNotesView } from "@vscode/webview-ui/src/components/DirectoryNotesView";
import type { ResourceNotesViewModel } from "@vscode/webview-ui/src/types";

describe("DirectoryNotesView", () => {
  it("renders compact child rows and prints the generated markup", () => {
    const notes: Extract<ResourceNotesViewModel, { kind: "directory" }> = {
      kind: "directory",
      name: "components",
      relativePath: "src/components",
      fileNote: {
        userNote: "Reusable interface components.\nShared across the application.",
      },
      children: [
        {
          kind: "file",
          name: "Button.tsx",
          relativePath: "src/components/Button.tsx",
          notePreview: "Renders the primary application button.",
        },
        {
          kind: "directory",
          name: "configuration-panels",
          relativePath: "src/components/configuration-panels",
          notePreview:
            "Contains configuration panels with a deliberately long explanation that should remain on one visual row.",
        },
      ],
    };

    const markup = renderToStaticMarkup(<DirectoryNotesView notes={notes} />);

    console.log("Directory notes markup:\n" + formatMarkup(markup));

    expect(markup).toContain("child-list__item");
    expect(markup).toContain("Shared across the application.");
    expect(markup).toContain("user-note-edit-button");
    expect(markup).toContain("Button.tsx");
    expect(markup).toContain("Renders the primary application button.");
    expect(markup).toContain("configuration-panels");
    expect(markup).toContain("deliberately long explanation");
    expect(markup).not.toContain("src/components/Button.tsx");
    expect(markup).not.toContain("src/components/configuration-panels");
    expect(markup).not.toContain("child-list__path");
    expect(markup).not.toContain("child-list__kind");
  });
});

/**
 * Adds line breaks between adjacent HTML tags for readable test output.
 *
 * @param markup - Static HTML markup generated by React.
 * @returns Markup with one adjacent tag boundary per line.
 */
function formatMarkup(markup: string): string {
  return markup.replaceAll("><", ">\n<");
}
