/**
 * Common shared types used across the core explanation models.
 */

/**
 * Supported programming languages for the MVP.
 */
export type Language = "ts" | "tsx" | "js" | "jsx";

/**
 * A line range within a source file.
 *
 * Both startLine and endLine are 1-based and inclusive.
 */
export type Range = {
  startLine: number;
  endLine: number;
};

/**
 * The smallest reusable explanation structure.
 * Complete explanation content attached to a node.
 */
export type ExplanationBlock = {
  /** Short explanation. */
  summary: string;

  /** Detailed explanation. */
  detail: string;

  /** Additional notes generated by the AI. */
  aiNotes?: string[];

  /** Notes manually added by the user. */
  userNotes?: string[];
};
