/**
 * Types for semantic units generated by the AI.
 *
 * Semantic units describe logical sections of a file, such as
 * state management, event handling, data fetching, or UI rendering.
 */

import type { ExplanationBlock, Range } from "./common";

/**
 * A logical section identified by the AI.
 *
 * Unlike StructureUnit, this is not necessarily a direct syntax node.
 * It is based on how humans understand the code.
 */
export type SemanticUnit = {
  /** Stable unique identifier. */
  id: string;

  /** Human-readable section title. */
  title: string;

  /** Source range covered by this semantic section. */
  range: Range;

  /** AI-generated explanation. */
  explanation: ExplanationBlock;
};
