/**
 * Shared types for AI-generated code analysis.
 */

/**
 * Structured explanation generated by an AI provider.
 *
 * This model contains AI-generated content only.
 * It must not include user notes, domain status, or persistence metadata.
 */
export type AIExplanation = {
  /** A concise explanation for quickly understanding the code. */
  summary: string;

  /** A detailed explanation of the code's responsibility and behaviour. */
  detail: string;

  /**
   * Additional insights, warnings, edge cases,
   * or important details that deserve separate visual emphasis.
   */
  aiNotes?: string[];
};
